---
title: "R Final Project"
author: "Caroline Baker, Yu Sun, Yagmur Yavuz Ozdemir"
date: "11/11/2021"
output: html_document
---

## Caroline 

```{r}
my_lm = function(y, X) {
  
y <- as.vector(y)
X <- as.matrix(X)
 

col <- rep(1,n)
n <- length(y)
X[,1] <- rep(1,n)
p <- dim(X)[2]
df <- n - p

beta.hat <- solve(t(X)%*%X)%*%t(X)%*%y

return(beta.hat)
}

```

## Confidence 

```{r}
my_lm = function(y, X, alpha = 0.05) {
  
  y <- as.vector(y)
  X <- as.matrix(X)
  
  n <- length(y)
  p <- dim(X)[2]
  df <- n - p
  
  beta.hat <- solve(t(X)%*%X)%*%t(X)%*%response
 
  resid <- y - X%*%as.matrix(beta.hat) 
  sigma2.hat <- (1/df)*t(resid)%*%resid
  
  
  var.beta <- sigma2.hat*solve(t(X)%*%X)
  
  quant <- 1 - alpha/2
  ci.beta <- c(beta.hat - qnorm(p = quant)*sqrt(var.beta), beta.hat + 
                 qnorm(p = quant)*sqrt(var.beta))
  
  return(list(beta = beta.hat, sigma2 = sigma2.hat, 
              variance_beta = var.beta, ci = ci.beta))
}
```

```{r}
library(ggplot2)
```










```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```
